### ISSUE TITLE
Another ch3 issue? 

### ISSUE THREAD

**Issue by jamestricker** [scrose/pylc#3]
Hey Spencer, I have just encountered an issue that may be similar to Maya's. I'm getting the following error message when I try produce masks for colour images using the ch3 2_2 model. This issue only appears when I run the model at 1.0 scale. The model seems to run no problem at lower scales including 0.9, although it perhaps seems to be taking a little longer than usual to run. I'll send you the image via slack. 
![Capture](https://user-images.githubusercontent.com/77693753/109601773-55702380-7ad4-11eb-9a5c-db65544b91fe.JPG)

**Comment by scrose** [comment]
The error is due to the extraction buffer being too small for all of the generated tiles. But it should not be generating 713 tiles, that's way too many for the image size. Can you provide a link to the image?

**Comment by jamestricker** [comment]
Its in your slack channel! Or I can send it another way if preferable?

**Comment by scrose** [comment]
Actually, nevermind -- I forget that the number of tiles will increase quadratically with dimension increases. I pushed a new version of pylc that you can use to test very large files. There's a parameter called "tiling_factor" in config.py. So, for 713 tiles at full scale, you'd want a factor of at least 713. You can tweak this value when you want to test very large files. Let me know how it goes.

**Comment by jamestricker** [comment]
Awesome - thank you Spencer!

**Comment by jamestricker** [comment]
Ok, think I changed the parameter correctly but it still won't run - getting a msg saying "Data array reached capacity. Increase the number of tiles per image". Here's the console output. Note that I'm still using the original models - I just downloaded the new version
[Output.txt](https://github.com/scrose/pylc/files/6072434/Output.txt)
 of pylc

**Comment by scrose** [comment]
OK, made another update. Try it now.

________________________________

**Comment by jamestricker** [comment]
That's it fixed - thanks so much Spencer :)
